#!/bin/bash
set -e

version=$(git rev-parse --short=8 HEAD)
tagName=192.168.1.2:32000/money-printers:$version

function main {
    echo "Building $version"

    checkoutAndRun $version build
}

function checkoutAndRun {
    if [ -d build/.git ]; then
        git worktree remove build
    fi
    if [ -d build ]; then
        rm -R build
    fi
    git worktree add -f build $1
    (cd build; $2)
    git worktree remove build
}

function build {
    (cd backend && ./gradlew build)
    (cd frontend && npm ci && ng build)
    sudo docker build -t $tagName .

    #docker login 192.168.1.2:32000
    sudo docker push $tagName
}

main
