apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: money-printers
spec:
  ingressClassName: public
  tls:
  - hosts:
    - daan.se
    secretName: daan-se-tls
  rules:
  - host: daan.se
    http:
      paths:
      - path: /money-printers
        pathType: Prefix
        backend:
          service:
            name: money-printers
            port:
              name: http
